### ISSUE TITLE
Hello, can you give a tutorial on building the environment?

### ISSUE THREAD

**Issue by 755713372** [BeatTogether/BeatTogether.MasterServer#14]
What kind of running environment does the server need? I tried it myself, but it can't be installed. I want to consult the specific installation process. Thank you very much.

**Comment by Kevman95** [comment]
Please join our discord server for assistance.

**Comment by 755713372** [comment]
Is there a link to the communication platform?

**Comment by Kevman95** [comment]
https://discord.com/invite/gezGrFG4tz

**Comment by 755713372** [comment]
Thank you very much.
