### ISSUE TITLE
[Request] Add Redis configuration file

### ISSUE THREAD

**Issue by jcoenen96** [BeatTogether/BeatTogether.MasterServer#2]
I've been trying to experiment with the mod and the server but the server crashes on a Redis exception. 

`Wrong number of args calling Redis command From Lua script`

BeatTogether.MasterServer.Data/Implementations/Repositories/ServerRepository Line 64
Being called by
BeatTogether.MasterServer.Kernel/Implementations/UserService Line 119

I think this is due to the fact that I don't have Redis configured correctly.

Could you add the configuration file required for Redis to run?

**Comment by Kevman95** [comment]
The default Redis configuration file should run the Master Server without any issue.  We haven't had any issues doing so.

I don't see the need in bundling it with this package considering that the default config that comes with a Redis install works.  It shouldn't need any specialized config. Maybe try rebuilding it against our latest commits?

Also id keep in mind that this MasterServer implementation with our plugins is not really ready for any sort of use yet. It really isn't released publicly other than open sourcing our code thus far. 

Ill touch back on this issue after the fact if this is still occurring.

**Comment by jcoenen96** [comment]
I ran the server through visual studio and installed Redis on windows. After trying to create a game in beat saber it crashed on the addserver.lua script. Might be some useful information for you.

**Comment by pythonology** [comment]
Which Redis version are you running?

Older versions of the Redis may have commands that have changed since.
For reference it's working for me on version `6.0.4`.

**Comment by jcoenen96** [comment]
it was indeed my Redis version. Now it is running fine, my apologies.
